### ISSUE TITLE
Bug: Fehlerseite bei Suche nach sgsid:xxx

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#106]
**Beschreibung**
Wenn man spezifisch nach einer SGS-Id sucht mit dem Suchinput z.B. sgsid:1703, dann taucht eine Fehlerseite auf.

**Schritte zum Reproduzieren**
1. Gehe auf assets
2. Schreibe "sgsid:1703" in das Suchfeld
3. Eine Fehlerseite erscheint

**Beobachtetes Verhalten**
Eine Fehlerseite erscheint.

**Erwartetes Verhalten**
Die Karte bleibt bestehen. Die Ergebnisse werden wie gewohnt angezeigt.
Auch wenn der Backend Call einen Fehler meldet, sollte an diesem Ort nicht auf die Fehlerseite weitergeleitet werden. Das ist nicht benutzerfreundlich.

**Screenshots**
![image](https://github.com/swisstopo/swissgeol-assets-suite/assets/103118462/b3800e77-487e-44e3-825c-2e1aeced767c)
![image](https://github.com/swisstopo/swissgeol-assets-suite/assets/103118462/25901036-063d-4cc6-905a-938078fbb058)

**Comment by daniel-va** [comment]
Anzeige der Error-Page wurde mit Popup-Alerts ersetzt. Die Suche selbst wird mit dem Deployment von #102 wieder funktionieren.

**Comment by mPfifi** [comment]
Test: Suche nach sgsid funktioniert auf DEV wieder ohne Probleme.
