### ISSUE TITLE
Suchergebnisse als Tabelle anstatt Kacheln

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#115]
**Beschreibung**

Zeige die Suchergebnisse als Tabelle an anstatt Kacheln. Die Ergebnisse sollen ausserdem unten in einem horizontalem Container angezeigt werden, der auch versteckt werden kann.
Siehe https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7296%3A48064&t=rbPWrhKqXCHxOFsz-1

**Acceptance Criteria**

 - [ ] Die Suchergebnisse sind als Tabelle sichtbar

**Comment by daniel-va** [comment]
@mPfifi Zum Testen auf INT verfügbar.

**Comment by mPfifi** [comment]
Sieht gut aus so und funktioniert korrekt
