### ISSUE TITLE
User Menu wandert nach oben rechts

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#119]
**Beschreibung**

Das User Menu wird in der Toolbar oben rechts angezeigt anstatt links unten.
Siehe https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7296%3A41642&t=rbPWrhKqXCHxOFsz-1

**Comment by daniel-va** [comment]
@vej-ananas If I understand this task correctly, then it has already been included in #285.
