### ISSUE TITLE
Filter "Keine Sprache" bei Suchfiltern

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#138]
**Beschreibung**

Bei den Filtern nach Sprache soll es auch die Option "Keine Sprache" geben. Derzeit werden Assets ohne Sprachzuweisung dann angezeigt, wenn alle verfügbaren Sprachoptionen ausgewählt sind. Die Option "Keine Sprache" ist lediglich in den Suchfiltern notwendig, nicht beim Bearbeiten eines Assets. "Keine Sprache" zeigt Suchresultate, die keiner Sprache zugeordnet sind.

**Comment by daniel-va** [comment]
@mPfifi Zum Testen auf INT verfügbar.

**Comment by mPfifi** [comment]
Ist vorhanden und funktioniert auf INT
