### ISSUE TITLE
Understand auth concept

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#15]
- How does Authentication and Authorization work in Assets? (Goal: get rid of Assets login mechanism)
- Document findings in Confluence
- What steps/measure need to be taken for migration to eIAM

Note: Schedule 1 person from GeoW for deployment support
- Unique identifier (subjectID, OIDC): Cognito or eIAM (tbd)

**Comment by TIL-EBP** [comment]
Ein Überblick ist hier zu finden : 
[Auth Concept](https://ebpgroup.atlassian.net/wiki/spaces/223443/pages/2025455619/Auth+Concept+Assets)
