### ISSUE TITLE
Bug: File download schlägt fehl

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#150]
**Beschreibung**
Wenn man ein File herunterladen oder in einem neuen Tab öffnen will, so schlägt das Fehl.
Es scheint keine Authentifizierung vorhanden zu sein.
Siehe Diskussion der Lösungsvarianten hier https://stackoverflow.com/questions/29452031/how-to-handle-file-downloads-with-jwt-based-authentication

**Schritte zum Reproduzieren**
1. Asset Detailansicht
2. File Download oder im neuen Fenster öffnen
3. Es erscheint die Fehlermeldung «error: no token found».

**Beobachtetes Verhalten**
Eine Fehlermeldung

**Erwartetes Verhalten**
Das File wird heruntergeladen.

**Comment by mPfifi** [comment]
@daniel-va Wie/Wo kann ich das derzeit testen? - Auf DEV und INT haben wir die pdf-Dateien ja nicht angehängt, somit erscheint der nach wie vor die Fehlermeldung.
Nach dem Deploy morgen werde ich es aber auf PROD sicher testen.

**Comment by mPfifi** [comment]
@daniel-va Auf PROD getestet, Download funktioniert. Lediglich besonders bei grösseren pdf-Dateien dauert es etwas länger, bis man erkennen kann, dass die Datei heruntergeladen wird. 
Gemäss Besprechung mit @vej-ananas soll das in einer ersten schnellen Problemlösung mit einem Spinner abgefangen werden. Ansonsten ist dieses Ticket aber abgeschlossen.
