### ISSUE TITLE
Packages auf swissgeol (GIT) zügeln

### ISSUE THREAD

**Issue by ga-ebp** [swisstopo/swissgeol-assets-suite#156]
Momentan werden noch zwei Packages aus GIT-geoadmin verwendet.
- https://github.com/orgs/geoadmin/packages/container/package/swissgeol-search-elasticsearch
- https://github.com/orgs/geoadmin/packages/container/package/swissgeol-search-kibana

Diese sollten auch verschoben werden.
Eventuell auch gerade auf neuste Version aktuallisieren?

**Comment by daniel-va** [comment]
Elasticsearch und Kibana sind im DEV auf die offiziellen Images in der Version `8.14.1` umgestellt.
Die Umstellung verlangt keine weiteren Eingriffe.

Das Deployment auf INT verfolgt nach Absprache mit swisstopo am nächsten Sprint-Meeting.
