### ISSUE TITLE
Progress-Spinner beim Download von Dateien

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#167]
**Beschreibung**

Der Download von Dateien hat derzeit keinerlei Anzeige. Grosse Dateien brauchen mehrere Sekunden.
Stelle einen Spinner anstelle des gekilckten Icons dar.
Das Icon daneben ist für den Zeitraum des Downloads deaktiviert.

**Acceptance Criteria**

 - [ ] Ein Spinner erscheint während des File-Downloads.

**Comment by mPfifi** [comment]
Getestet auf INT, hat gut funktioniert.
