### ISSUE TITLE
Fix Heatmap Generierung

### ISSUE THREAD

**Issue by ga-ebp** [swisstopo/swissgeol-assets-suite#172]
**Problem**: 
Auf Produktion wird beim starten der App die Headmap nicht dargestellt. Der Ladebalken wird immer angezeigt.

**Analyse**: 
Das Asset mit ID 44378 (Titel: "Arbeitsbericht NAB 06-26: Stratigrafie, Mächtigkeit und Lithofazies der mesozoischen Formation in der Nordschweiz") macht probleme.

**Workaround**:
Der View *all_study* wurde auf der DB angepasst, damit das entsprechende Asset nichtmehr zum Client geschickt wird.

CREATE OR REPLACE VIEW public.all_study
 AS
 SELECT study_area.asset_id,
    concat('study_area_', study_area.study_area_id::text) AS study_id,
    study_area.study_area_id AS id,
    study_area.geom,
    study_area.geom = st_centroid(study_area.geom) AS is_point,
    st_astext(st_centroid(study_area.geom)) AS centroid_geom_text,
    st_astext(study_area.geom) AS geom_text
   FROM study_area
UNION ALL
 SELECT study_location.asset_id,
    concat('study_location_', study_location.study_location_id::text) AS study_id,
    study_location.study_location_id AS id,
    study_location.geom,
    study_location.geom = st_centroid(study_location.geom) AS is_point,
    st_astext(st_centroid(study_location.geom)) AS centroid_geom_text,
    st_astext(study_location.geom) AS geom_text
   FROM study_location
  **WHERE study_location.asset_id <> 44378**
UNION ALL
 SELECT study_trace.asset_id,
    concat('study_trace_', study_trace.study_trace_id::text) AS study_id,
    study_trace.study_trace_id AS id,
    study_trace.geom,
    study_trace.geom = st_centroid(study_trace.geom) AS is_point,
    st_astext(st_centroid(study_trace.geom)) AS centroid_geom_text,
    st_astext(study_trace.geom) AS geom_text
   FROM study_trace;

**Comment by daniel-va** [comment]
Die problematische `study_location` existiert nicht mehr und das Problem kann derzeit nicht reproduziert werden. Wir beobachten weiter, ob das Problem erneut aufrtritt, können aber im momentanen Zustand der Applikation keine Fehlerbehebung angehen.
