### ISSUE TITLE
Release-Notes

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#174]
**Beschreibung**
DRAFT -> @vej-ananas Bitte ausformulieren
Als Benutzer/Tester von Assets möchte ich wissen, welcher Stand auf INT und PROD installiert ist. Hierfür braucht es Release-Notes.
(Boreholes erstellt die Release Notes "von Hand" -> bei Daniel nachfragen)

**Acceptance Criteria**
- [ ] Release-Notes werden erstellt und sind für den Benutzer/Tester abrufbar

**Comment by vej-ananas** [comment]
Release Notes sind bereits vorhanden hier: https://github.com/swisstopo/swissgeol-assets-suite/releases
Wir können allenfalls die einzelnen und teilweise unübersichtlichen Commit Nachrichten zusammenfassen.

**Comment by vej-ananas** [comment]
@mPfifi aktuelle Release Notes lassen sich ab sofort im File `CHANGELOG.md` finden.
Für DEV hier: https://github.com/swisstopo/swissgeol-assets-suite/blob/develop/CHANGELOG.md
Für INT hier (aber erst, nachdem wir wieder auf INT deployen): https://github.com/swisstopo/swissgeol-assets-suite/blob/main/CHANGELOG.md

**Comment by mPfifi** [comment]
@vej-ananas Merci für die Info! Kleine Frage: wird das Changelog bei jedem update neu erstellt oder jeweils bei jedem Deploy laufend aktualisiert, wobei die vorangehenden Einträge erhalten bleiben? Ich würde letzteres erwarten, damit alle Schritte dokumentiert bleiben...
