### ISSUE TITLE
Bug: Die Karte wird abgeschnitten dargestellt

### ISSUE THREAD

**Issue by DmByK** [swisstopo/swissgeol-assets-suite#182]
**Beschreibung**
Die Karte wird abgeschnitten dargestellt, nachdem eine Suche durchgeführt und anschließend Suchsteuerung zugeklappt wurde

**Schritte zum Reproduzieren**

1. Suche nach Asset
2. Klicke auf Assets links
3. Klicke auf Benuzterverwalung links
4. Klicke wieder auf Asset links

**Beobachtetes Verhalten**
Karte wird  wird abgeschnitten dargestellt

**Erwartetes Verhalten**

Die Darstellung der Karte ändert sich nicht

**Screenshots**
![Unbenannt1](https://github.com/swisstopo/swissgeol-assets-suite/assets/164023012/fb674638-6953-4601-ba5d-45f2b674fb2d)

**Plattform**
Chrome, Edge

**Comment by daniel-va** [comment]
Ist in der aktuellen Version (post #115) nicht mehr reproduzierbar.
