### ISSUE TITLE
Favoriten | Erstellung & Verwaltung (#18)

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#19]
Ein User soll die Möglichkeit haben, einzelne oder mehrere Assets bei der Suchtreffer- oder Detailviewanzeige als Favoriten markieren zu können (über den Stern, welcher pro Suchtreffer in Trefferliste oben rechts angezeigt wird).

Unter dem Tab Favoriten, sollen alle Favoriten eines Users anschliessend angezeigt werden können. Design und Funktionalität identisch wie unter Tab Assets. Alle Suchmöglichkeiten beziehen sich hier aber nur noch auf die Favoriten.

Anstelle der Heatmap sollen von Beginn an alle Geometrien der Favoriten angezeigt werden.

Es soll die Möglichkeit geben, dass bestehende Favoriten aus Favoritenliste wieder entfernt (gelöscht) werden können.

**Comment by traffic1000** [comment]
Is this still relevant now that a new OCR solution is being built?

**Comment by stijnvermeeren-swisstopo** [comment]
> zu einem späteren Zeitpunkt ggf. komplett überarbeiten

We are currently already doing this.

I think this ticket can be closed as not relevant anymore, and we will create a new ticket as soon as we are ready to integrate the new OCR service.

**Comment by mPfifi** [comment]
@vej-ananas : Funktioniert gemäss Tests 20.11.2024 sehr gut. Nur Editieren ist direkt aus den Favoriten nicht möglich, da kehrt die Applikation zunächst in die normale Suche zurück. Erst dann kann das Asset editiert/bearbeitet werden. Das ist soweit aber ok so und könnte sicher später noch angepasst werden.

**Comment by mPfifi** [comment]
Test 27.11.2024: Favoritenfunktion funktioniert weiterhin gut, ausser dem im vorangehenden Kommentar erwähnten Verhalten beim Editieren.
Kann 2025 angepasst werden (Pendenz)!
