### ISSUE TITLE
Suche verfeinern | Autor (#25)

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#20]
Issue taken from previous Taks list (# 25)
Comment Marcel: --> aktuell passt sich die Autorenliste bei Verfeinerung der Suche nicht automatisch dem neuen Suchresultat an!

Die Liste mit allen Autoren passt sich nicht der reduzierten Suche an, wenn die Suche zuerst mit einem anderen Filter verfeinert wird z.B. nach Polygonsuche mit Nutzungs Filter und dann erst Autor.
Comment: Close: macht keinen Sinn dies dynamsich anzupassen da sonst gefahr läuft, dass man in ein "dead-end" läuft in kombination mit anderen Filteroptionen

**Comment by vej-ananas** [comment]
@mPfifi In diesem Issue steht am Ende "Comment: Close: ...". Ist das Issue trotzdem als Offen zu betrachten?

**Comment by mPfifi** [comment]
@vej-ananas Ja, das Issue ist dennoch als offen zu betrachten. Ich habe es aus den Pendenzen der früheren Entwicklungen mit Lambda-IT mitgenommen, da dies nach wie vor ein noch nicht gelöstes Problem bei der Verfeinerung der Suche bei den Autoren darstellt. Der "Comment: Close..." stammt noch von Lambda-IT.
Ich muss das Issue allerdings einmal noch etwas genauer ausformulieren.
