### ISSUE TITLE
Filter korrekt einschränken

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#205]
**Beschreibung**
Die Filter Funktionalität wurde inspiriert von Galaxus. Das Verhalten ist noch nicht ganz korrekt.

**Acceptance Criteria**

- [ ] Die Filter der Assets sollen anfangs alle unausgewählt sein. 
- [ ] Das Auswählen eines Filters schränkt die Filter der anderen Gruppierungen ein.

**Comment by mPfifi** [comment]
Scheint allgemein gut zu funktionieren, benötigt bei grösseren Suchresultaten einfach etwas Zeit...
