### ISSUE TITLE
UI Sidebar & Header anpassen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#206]
**Beschreibung**

Passe Sidebar und Header entsprechend des Figma Entwurfs an.

**Acceptance Criteria**

- [x] Icons stimmen überein mit Text on hover
- [x] Language selection wird dropdown
- [x] #119 User oben rechts
- [x] Direkter Butten in sidebar für User erstellen
- [x] Zahnrad links unten ist Admin View inklusive Elastic Sync Button und User + Workgroup Management
- [x] Suchfeld Aussehen angepasst
- [x] Suchfilter muss korrekt über Suchresultaten liegen - Z-Index erhöhen damit Schatten korrekt angezeigt werden

**Comment by vej-ananas** [comment]
@daniel-va Im Admin User und Workgroup Bereich werden  "+" icons anstatt editieren Icons angezeigt - gerne reverten.

**Comment by mPfifi** [comment]
@vej-ananas Sieht für mich soweit gut aus, einzig der direkte Button in sidebar für User-Erstellung kann ich nicht finden... - das geht nur für neue Assets und sonst über die Benutzerverwaltung resp. Cognito, korrekt?!
