### ISSUE TITLE
Bug: Stats produzieren 502 Fehler

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#219]
**Beschreibung**
Bei der schnellen Kombination mehrerer Suchfilter taucht manchmal ein 502 Fehler auf.

**Schritte zum Reproduzieren**
1. Gehe zur Home Seite
2. Wähle die folgenden Filter nacheinander mit je ~0.5s Unterbrechung
    a. Öffentliche Nutzung
    b. Polygon
    c. deutsch
4. Ein Fehler erscheint wie im Screenshot. Möglicherweise muss mehrmals probiert werden.

**Beobachtetes Verhalten**
Ein Fehler erscheint beim Laden der Stats nach mehrmaliger Filteränderung.

**Erwartetes Verhalten**
Kein Fehler erscheint.

**Screenshots**

![Image](https://github.com/user-attachments/assets/ab235b4e-3729-4643-903f-d71a48264b97)

**Comment by daniel-va** [comment]
Das ist soweit ich sehe ein Out-Of-Memory. Der Fehler trifft auf, wenn durch eine Vielzahl von Suchanfragen eine grosse Menge Suchresultate parallel verarbeitet werden. Ich sehe da mehere Ansätze zur Behebung:

- Limitieren der Anzahl von gleichzeitigen Suchen/Requests per Benutzer
- Abbruch von vorherigen Suchen wenn ein Benutzer eine neue Suche startet
- Mehr Memory
- Memory-Usage der Suche im Allgemeinen optimieren (z.B. durch Streaming, Pagination, o.Ä.). Der Fehler tritt hauptsächlich auf, da jede Suche 10'000 Assets vollständig ins Memory lädt.

**Comment by mPfifi** [comment]
Auf DEV getestet gemäss oben beschriebenem Vorgehen: der Fehler **502 Bad Gateway** erscheint nach wie vor.

**Comment by mPfifi** [comment]
Fehler ist auf INT soweit nicht mehr aufgetreten...
--> Verhalten ggf. weiter beobachten, Task jedoch schliessen.
