### ISSUE TITLE
Bug: Polygon Selector öffnet Detailauswahl

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#220]
**Beschreibung**
Beim platzieren eines Polygons zur weiteren Einschränkung eines Suchresultats erscheint der Detailselektror der Assets. Das sollte nicht der Fall sein.

**Schritte zum Reproduzieren**

1. Starte eine Suche
2. Schränke die Suchresultate über ein Polygon ein
3. Jeder Click mit dem Polygon-Tool über ein bestehendes rotes Suchresultat öffnet die Detailauswahl
4. Ein Fehler 

**Beobachtetes Verhalten**
Die Detailauswahl öffnet sich.

**Erwartetes Verhalten**
Das Polygon kann ohne Unterbrechung gemalt werden.

**Screenshots**

![Image](https://github.com/user-attachments/assets/861a6dae-d714-46fb-971c-42d15d916d63)

**Comment by mPfifi** [comment]
@daniel-va , @vej-ananas : ich habe das gerade kurz auf DEV getestet (auf INT ist es noch nicht implementiert, oder?) und festgestellt, dass das Popup-Fenster nach wie vor erscheint, aber erst beim Schliessen des mit dem Polygonwerkzeug gezeichneten Polygons, entweder mittels Doppelklick oder Klicken auf den ersten gezeichneten Punkt der Polygons. Dies sollte nicht sein, das Popup-Fenster darf nur erscheinen, wenn ich ohne Polygon-Werkzeug direkt auf Objekte klicke, welche in der ersten Suche gefunden worden sind.

Die im Popup-Fenster erscheinende Anzahl Suchtreffer unterscheidet sich zudem von der Anzahl Treffer, welche mit dem Polygon eingegrenzt worden sind.

![Image](https://github.com/user-attachments/assets/6b445c96-7a7c-4f6e-83a2-3f2c44dc801a)

Hier muss noch etwas nachgebessert werden... - merci vielmals!

**Comment by mPfifi** [comment]
Auf DEV getestet und i.O. - auf INT noch nicht implementiert.

**Comment by mPfifi** [comment]
Funktioniert auch auf INT, ohne dass popup-Fenster erscheint. --> ok, Task abgeschlossen.
