### ISSUE TITLE
Bug: Autoren Liste in Filtern unschön

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#221]
**Beschreibung**
Die Auswahl der Autoren in den Filtern wird unschön dargestellt.

**Beobachtetes Verhalten**

![Image](https://github.com/user-attachments/assets/1471e96f-a43e-4c35-b12c-39a25b6881a7)

**Erwartetes Verhalten**
Zumindest wie auf Prod:

![Image](https://github.com/user-attachments/assets/dbb3aee9-6172-4335-bdf0-6ed5a17af0f9)

**Comment by mPfifi** [comment]
Auf DEV getestet und i.O.

**Comment by mPfifi** [comment]
Sieht auch auf INT nur wieder sehr schön aus. Es lässt sich auch schön nach Autoren eingrenzen/suchen über die Suchsteuerung.
--> Task abgeschlossen.
