### ISSUE TITLE
Anfangsdatum im Filter "Datum von" anpassen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#222]
**Beschreibung**

Der Filter "Datum von" fängt derzeit beim minimalen verfügbaren Datum an, wenn man die Kalenderauswahl öffnet.
Ändere die Ansicht, damit frühestens 1800 gezeigt wird.

Also `max(1800, createDateRange?.min)`

**Comment by daniel-va** [comment]
Der Filter nimmt das kleinste Erstellungsdatum aller existierenden Assets als Minimalwert machen. Würde es hier nicht mehr Sinn machen, das Erstellungsdatum aller Assets, die vor 1800 liegen, auf diesen Wert zu ändern? Ich nehme mal an dass werte wie `0164` und `1600` sowieso falsch sind.

**Comment by mPfifi** [comment]
Auf DEV getestet, sieht gut aus. Start bei 1800 und Anpassung in Vergangenheit und Zukunft möglich, passt so.

**Comment by mPfifi** [comment]
Dito auf INT --> erledigt!
