### ISSUE TITLE
Bug:  Rauten von Studies

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#230]
**Beschreibung**
Bei Studies sollen die Mittelpunkte von Flächen wie zuvor als Rauten dargestellt werden.

**Beobachtetes Verhalten**

![Image](https://github.com/user-attachments/assets/b3167f3b-7e46-4f1a-9879-e2279360737e)

**Erwartetes Verhalten**

![Image](https://github.com/user-attachments/assets/7f6b5289-f094-46ac-8b4b-a7eee6a40a6a)

**Comment by mPfifi** [comment]
Mittelpunkte von Flächen und Linien werden wieder mittels Rautensymbol dargestellt.
--> ok und erledigt.
