### ISSUE TITLE
Bug: Fehler bei gleichem Workgroup-Namen ordentlich anzeigen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#238]
**Beschreibung**
Wenn beim Erstellen oder Bearbeiten einer Workgroup ein Name eingegeben wird, der bereits bei einer anderen Workgroup benutzt wird, so erscheint ein 500 Internal server error.

**Schritte zum Reproduzieren**

1. Erstelle eine neue Workgroup
2. Wähle einen Namen, den eine bereits existierende Workgroup hat
3. Ein 500 Internal server error erscheint

**Beobachtetes Verhalten**
Der Fehler wird als Internal Server Error kommuniziert

**Erwartetes Verhalten**
Dem Benutzer wird kommuniziert, dass es bereits eine Workgroup mit diesem Namen gibt

**Comment by mPfifi** [comment]
@vej-ananas Funktioniert, Fehlermeldung/Hinweis erscheint und ist verständlich und erscheint, wenn man neue Workgroup mit bereits bestehendem Namen zufügen möchte.
