### ISSUE TITLE
View-Mode | Mark search results red on map  (#60)

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#24]
Issue taken from previous Taks list (# 60)
Comment Marcel: --> auch für blau dargestellte Symbole direkt!

- Der Nutzer soll die Möglichkeit erhalten per Maus-Click Objektinformation eines Punkte/Raute auf der Karte abzufragen. Beim Maus-Click auf das Objekt auf der Karte öffnet sich das "Detailinformation"-Panel. (Not part of this story. See Issue #27)
- Bei einer Vorgängigen Suche und einem Click auf die Karte sollen die Objekte, die aus der Suche hervorgegangen sind von sonstigen Objekten an dieser Stelle in den Mehrfach Resultaten farblich unterschieden werden. Rot: Resultat aus Suche; blau: Objekt an dieser Stelle nicht aus Suche -> merge filter function (search bar) with map selection; don't hide "blue" points, just flag the selected ones in red

**Acceptance criteria:**
1. Results from a search are marked Red instead of Blue on the map. Similar behavior is present when selecting multiple objects via multi-polygon

**Comment by vej-ananas** [comment]
Dieses Verhalten wurde im Verlauf des Search-Refactorings erreicht.
