### ISSUE TITLE
Bug: Suche und URL out of Sync

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#240]
**Beschreibung**
Die Suchfilter und URL gehen out of Sync, wenn man auf andere Seiten navigiert.

Wenn man eine , auf eine andere Seite wie Asset Management navigiert und wieder auf Asset Map klickt, dann 
**Schritte zum Reproduzieren**

1. Suche starten z.B. durch einen Suchfilter
2. Auf eine andere Seite wie Asset Management navigieren
3. Über Sidebar wieder auf Asset Map navigieren
4. Filter sind gesetzt wie zuvor, aber die URL ist leer `https://dev-assets.swissgeol.ch/de`

**Beobachtetes Verhalten**
URL leert sich durch navigation

**Erwartetes Verhalten**
URL und Filter stellen ein einheitliches Bild dar.

**Comment by mPfifi** [comment]
@vej-ananas Ich habe auch hier etwas herumgespielt und das Verhalten beobachtet - jeweils im Vergleich zwischen PROD und DEV. Das Verhalten der Applikation ist auf DEV deutlich stabiler und meist, wie ich es erwarten würde - ausser wenn zunächst über eine Polygonsuche gestartet wird. Da geht bei Auswahl eines Assets aus der Trefferliste und anschliessendem Wechsel in den Bearbeitungsmodus und zurück die Detailansicht von vorher verloren.

Vorgehen:
1. Auswahl über Polygonsuche
2. Selektion eines Assets auf der Trefferliste --> Detailansichtsfenster öffnet sich auf rechter Seite, Karte zoomt zu Asset
3. Wechsel in Bearbeitungsmodus über Bleistiftsymbol --> Asset kann bearbeitet werden
4. Verlassen des Bearbeitungsmodus über Zurück-button des Browsers (Edge)
5. Liste aus Polygonsuche wird angezeigt, die vorangehende Detailansicht des ausgewählten Assets geht jedoch verloren.

Anstelle von Schritt 3 oben kann auch zu "Verwaltung" oder "Benutzer verwalten" gewechselt werden und zurück, auch hier geht die Detailansicht verloren während die Liste erhalten bleibt.

Erwartetes Verhalten:
Die Detailansicht des ausgewählten Assets bleibt erhalten - wie es bei anderem Suchvorgang auch umgesetzt ist, z.B. wenn ich über ein Stichwort oder über "Suche verfeinern" einsteige.

**Comment by vej-ananas** [comment]
@mPfifi Das verhalten sollte nun wie erwartet sein.

**Comment by mPfifi** [comment]
@vej-ananas Ich habe das mit der Polygonsuche und auch das andere Verhalten nochmals kurz getestet - funktioniert soweit tadellos und einheitlich. Ich kann nach den Ferien nochmals etwas genauer testen, soweit konnte ich aber kein Fehlverhalten mehr feststellen.
