### ISSUE TITLE
Workgroups

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#244]
The finished Workgroup milestone.

**Comment by mPfifi** [comment]
@vej-ananas : Test der Workgroups auf Assets-INT - Feststellungen:

- Benutzerverwaltung und Verwaltung der Workgroups funktioniert gut, keine Fehler/Fehlermeldungen festgestellt.
- einzig beim Erstellen einer neuen Workgroup erscheint diese in der Liste der Arbeitsgruppen zunächst doppelt, bis die Seite neu geladen wird:

![Image](https://github.com/user-attachments/assets/9ad98975-856c-436d-8d43-55766d391892)

Dies ist zwar ggf. etwas irritierend, aber nicht gravierend und kann auch später behoben werden.

- Dasselbe gilt teilweise auch bei der Nutzerverwaltung: nach Änderungen muss die Seite ggf. zuerst neu geladen werden, bis die Änderungen korrekt dargestellt werden.
- Die Zuweisung von Assets zu einer bestimmten Workgroup muss momentan pro Asset einzeln erfolgen. Hier wäre es gut, wenn zukünftig mehrere Assets resp. eine ganze Liste ausgewählt und dann zugleich einer anderen Workgroup zugewiesen werden könnten. Hierzu kann allenfalls bereits ein Ticket für die Weiterentwicklung erstellt werden, merci vielmals!

Abgesehen davon ist die Verwaltung von Workgroups und Benutzern aber sehr gut gelungen, benutzerfreundlich und selbsterklärend, wirklich toll!

**Comment by mPfifi** [comment]
@vej-ananas Ich habe beim Testen der Workgroups gerade folgendes festgestellt (als Admin, mit verschiedenen Rollen in den einzelnen Workgroups): 
- ich kann auch die Assets jener Workgroups sehen, in welchen ich sonst gar nicht registriert bin (weder Viewer noch Editor oder Master Editor).
- ich kann diese Assets, in deren Workgroup ich gar nicht registriert bin, zumindest teilweise auch bearbeiten, erhalte teilweise aber auch die Meldung "Sie haben keinen Zugriff auf diese Ressource." (besonders wenn ich die Freigaben und Verweise bearbeiten möchte, bei den Verweisen geht es meist gar nicht).

Ich würde erwarten, dass ich jene Workgroups, zu welchen ich nicht zugeteilt bin, als Admin zwar verwalten, nicht aber auf die darin enthaltenen Assets selber zugreifen kann. Oder dann habe ich als Admin Vollzugriff auf alles unabhängig von den zugewiesenen Rollen in den einzelnen Workgroups. Derzeit scheint es aber eine Mischung aus diesen beiden Varianten zu sein.
Eigentlich sollte ich doch ganz allgemein nur auf Assets in jenen Workgroups Zugang haben, in welchen ich auch eine bestimmte Rolle habe (Viewer, Editor, Master Editor), und als Admin kommt dann noch die Benutzer- und Workgroup-Verwaltung dazu, oder?!?

Hier scheint etwas noch nicht ganz 100%-ig zu funktionieren. Ich werde das Anfang kommende Woche auch noch mit Kollegen in verschiedenen Rollen testen lassen. Gerne können wir das auch kommende Woche mal noch besprechen.

**Comment by mPfifi** [comment]
@vej-ananas Ich habe das Verhalten mit den Workgroups und den jeweils zugewiesenen Rechten noch mit zwei Kollegen getestet, jeweils mit verschiedenen Rollen (Viewer, Editor, Master Editor) und verschiedenen Workgroups.

Dabei hat alles wie erwartet geklappt:
- man kann nur Einträge in jenen Workgroups sehen, in welchen man auch mindestens Viewer-Rechte hat, die anderen Workgroups sieht man nicht. --> ok!
- ein Viewer kann nur Daten durchsuchen, aber nicht ändern/erfassen. --> ok!
- Editieren/neu erfassen kann man nur als Editor oder Master Editor, nicht aber als Viewer. --> ok!
- Master Editor kann zusätzlich unter Nutzung den Status ändern und ein Assets publizieren (unter Administration), was ein Editor nicht kann. --> ok!

Das oben erwähnte Problem tritt also nur in der zusätzlichen Rolle "Admin" auf und ist dementsprechend auch weniger gravierend.
