### ISSUE TITLE
Admins sollen Workgroup Regeln unterliegen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#252]
**Beschreibung**
Admins sollen den Workgroup Regeln unterliegen für Editor und MasterEditor Funktionalitäten.
Admins haben immer mindestens Viewer für alle Workgroups.

**Acceptance Criteria**

- [ ] Admins können alle Workgroups und deren Assets sehen, auch ohne Workgroup.Viewer Rolle
- [ ] Admins können nur Assets bearbeiten, wenn sie die entsprechende Workgroup.Rolle haben

**Comment by mPfifi** [comment]
@vej-ananas Ich habe das gerade getestet, und das Verhalten entspricht noch nicht ganz dem erwarteten Verhalten, indem:
- ich in der Rolle "Editor" im Reiter "Nutzung" die Externe Nutzung bearbeiten und speichern kann, nicht aber die Interne Nutzung (da wird eine Fehlermeldung ausgegeben). Eine Bearbeitung der Nutzung sollte in der Editor-Rolle aber nicht möglich sein.
- ich ebenfalls in der Rolle "Editor" im Reiter "Administration" den Arbeitsstatus auf "Publiziert" stellen kann, was in der Rolle Editor ebenfalls nicht möglich sein sollte.

Könntest du das nochmals anschauen? Merci vielmals!

**Comment by vej-ananas** [comment]
@mPfifi ich habe das Folge-Issue https://github.com/swisstopo/swissgeol-assets-suite/issues/309 erstelllt
