### ISSUE TITLE
Verweise müssen in derselben Workgroup sein wie Asset

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#253]
**Beschreibung**

Ein Asset darf nur Verweise haben auf andere Assets in derselben Workgroup.
Es folgt, dass ein Asset nur einer anderen Workgroup zugeordnet werden kann, sofern es keine Verweise besitzt.

**Acceptance Criteria**

- [ ] Beim Zuordnen von Verweisen sind nur Assets derselben Workgroups auswählbar
- [ ] Ein Asset mit Verweisen kann nicht einer anderen Workgroup zugeordnet werden

**Comment by mPfifi** [comment]
Funktioniert auf DEV korrekt, Wechsel der Workgroup nur möglich, wenn Verweise entfernt werden.

**Comment by mPfifi** [comment]
Funktioniert weiterhin korrekt. 
Falls von früheren Arbeiten aber bereits Verweise auf eine andere Workgroup vorhanden sind, lassen sich beim Editieren Änderungen nicht speichern, bis die "fehlerhaften" Verweise entfernt sind. Die Applikation gelangt in Endlosschlaufe, es wird aber keine Fehlermeldung ausgegeben, nur in den devTools des Browsers erscheint eine Fehlermeldung:

![Image](https://github.com/user-attachments/assets/cdcaebff-cf71-41c1-ac8f-32bf132d9e95)

Ist aber kein Fehler, sondern konsistentes Verhalten der Applikation.
--> Bereits bestehende Verweise zwischen Workgroups sollten entfernt werden, um dies zu verhindern.
