### ISSUE TITLE
Feedback 02.05.2023 (#71)

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#26]
Issue taken from previous Taks list (# 71)
Comment Marcel: --> offene Fragen zum Schluss von GAIA!

**Grundsätzliches Feedback:**
- Suche und Erfassung funktionieren intuitiv und gut!

**Anpassungswünsche, sofern noch Budget nach der Migration besteht:**
- Auto-Logout: Prüfen, ob das Handling des Accesstoken ausgebaut wird, oder ob der Ablauf des Accesstokens verlängert wird: Aufwand (ca. 2 - 3 Stunden)
- Verweise Tab: SGS_ID und Assed_Id suchbar machen und darstellen: Aufwand ca. 3 Stunden
- Wertelisten Typ; Format; Thema; "Nationales Interessse"; Arbeitsstatus alphabetisch pro Sprache sortieren: Aufwand ca. 1.5 Stunden
- [x] BUG: Pop mit speichern.

**Comment by vej-ananas** [comment]
stale
