### ISSUE TITLE
Bug: Autoren Filter nicht vollständig

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#263]
**Beschreibung**
Der Filter für Autoren von Assets in der Suche ist nicht vollständig.

**Schritte zum Reproduzieren**

1. Gehe zur Homepage. Im Filter Autor erscheint SBB nicht:

![Image](https://github.com/user-attachments/assets/85744547-44c2-4b14-a6b5-81b738b62909)

2. Gebe "SBB" als Suchtext ein in der Textsuche oben

![Image](https://github.com/user-attachments/assets/fbf8812b-07ef-464c-8a6c-3e871a49b54e)

3. Nun erscheint SBB als Autor:

![Image](https://github.com/user-attachments/assets/3c085db2-940e-4469-b2c6-d7613686f717)

**Erwartetes Verhalten**
SBB und alle anderen Autoren, die im Ergebnisset vorhanden sind, sollten jederzeit durch Durchsuchen des Autoselect auffindbar sein.

**Comment by mPfifi** [comment]
@vej-ananas Ich habe dies kurz auf DEV getestet und mit PROD verglichen - sieht nun schon viel besser und vollständig aus. So kann jederzeit nach allen verfügbaren Autoren gesucht werden.

--> Kann aus meiner Sicht so auf INT und PROD deployed werden.
