### ISSUE TITLE
Selection of points without having to draw polygons

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#27]
Currently, point features cannot be clicked on the map. They must be captured using the "Polygon selection" tool. 
As a user, I'd like to directly select an asset on the map without using the "polygon selection"

Question Rafael: Point selection as tool in toolbox (next to polygon selection)? Or is the point selection always active?

Direct or point selection tool next to polygon selection tool in toolbox would be nice. So the selection method can be chosen by the user itself. Before selecting one of the tools needs to be chosen. Otherwise there might be a conflict with the pan-function in the map (erroneous click on point feature instead of panning by user).

- Point selection
- "rectangle" mode (wie map.geo.admin); Ctrl. + Mouse

See also Issue #24 (backlog)!

**Acceptance criteria**
1. When clicking on an object in the map, the "Detailinformation"-Panel opens for the selected object.
2. In the toolbar there is a rectangle selection tool. It is also usable via Ctrl + Mouse.
3. When points are selected (e.g. via polygon tool), blue points are still selectable via e.g. clicking.

**Comment by mPfifi** [comment]
Konnte weder auf INT noch auf DEV getestet werden, resp. hat mit Direktklick auf blaues Symbol auf INT nicht funktioniert.
