### ISSUE TITLE
Entferne unbenutze Packages aus dem Source Code

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#282]
Es gibt Packages im Projekt, die nicht mehr genutzt werden. Diese sollen entfernt werden.
Teil des Issues ist das gründliche Nachtesten der Applikation nach dem Entfernen.

**Entfernen**
@Turf
monocle-ts
newtype-ts
node-fetch 
serialize-error
url-join
@types/multer
autoprefixer 
Postcss
postcss-import
postcss-preset-env
postcss-url
type-zoo

**Überprüfen**
@types/validator

Kobalte + solidjs
vite-plugin-solid

**Comment by daniel-va** [comment]
@vej-ananas 
 
- `@types/validator` can be removed without issue.
- `@types/multer` is used in NestJS routes that support file uploads.
- `kobalte` is used to display the tabs in the Asset Editor - replacing these is IMO out of scope of this Issue. It would include fully replacing `libs/ngx-kobalte`, which would also allow us to remove any dependencies related to`kobalte`, `solid-js`, `vite` and `rollup`.
