### ISSUE TITLE
Assets löschen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#293]
**Beschreibung**

Als Administrator will ich ein Asset löschen können.
Implementiere dafür ein Cascade, damit alle verwandten Objekte ebenfalls gelöscht werden.
Es muss zumindest 2 Mal geklickt werden - löschen + bestätigen.
Dateien werden auch von S3 gelöscht, sofern sie sonst nicht benutzt werden.

**Acceptance Criteria**

- [ ] Administratoren können Assets löschen.

**Comment by mPfifi** [comment]
Assets lassen sich nun löschen, ohne dass die DropDown-Listen verändert werden - jedenfalls gemäss einem Test.
Die DropDown-Listen sind jedoch auf DEV und INT im Vergleich zu PROD nun unvollständig (wegen dem Problem, dass Einträge beim Testen z.T. mit den Assets entfernt wurden) und sollten bei Gelegenheit wieder mit PROD abgeglichen werden.

**Comment by mPfifi** [comment]
DropDown-Listen wieder vollständig, löschen von Assets ist möglich, ohne dass die Listen verändert werden.
--> Issue nach done verschoben.
