### ISSUE TITLE
Autocomplete für Autoren im Edit-Asset Formular

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#294]
**Beschreibung**

Derzeit kann beim Auswählen von Kontakten die Liste von Autoren nicht eingegrenzt werden. Es soll möglich sein, durch geschriebenen Text die Liste zu filtern.

**Acceptance Criteria**

- [ ] Kontakte sollen durch Autocomplete durchsuchbar sein.

**Comment by mPfifi** [comment]
@vej-ananas Habe ich soeben getestet - funktioniert bestens! Autoren werden nun durch geschriebenen Text/Stichworte laufend eingegrenzt, was bei der Erfassung die Suche nach bereits bestehenden Kontakten stark erleichtert.
