### ISSUE TITLE
Gesamte Schweiz auch auf kleineren Laptop Bildschirmen sichtbar machen

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#296]
**Beschreibung**

Auf kleineren Bildschirmen verhindert der minimale Zoom, dass die gesamte Schweiz sichtbar ist. Passe den Zoom (entsprechend Boreholes) an, so dass auch auf kleineren Bildschirmen die gesamte Schweiz auf den Bildschirm passt.

**Acceptance Criteria**

- [ ] Die Schweiz ist initial sichtbar.

**Comment by mPfifi** [comment]
Zoomstufe beim Start der App angepasst, ganze Schweiz sollte auf Laptop gut sichtbar sein.

**Comment by mPfifi** [comment]
Test auf Laptop-Bildschirm (INT & DEV): Zoomstufe ist besser, Schweiz ist aber noch etwas angeschnitten (bei Schaffhausen, im Wallis und im Tessin):

![Image](https://github.com/user-attachments/assets/cb3b403c-c37b-42aa-b77a-d3c7b95efda5)

In boreholes ist die initiale Zoomstufe noch deutlich weiter rausgezoomt.
--> Muss 2025 noch etwas nachgebessert werden, daher Issue auf "Ready" zurückgesetzt.
