### ISSUE TITLE
Bug:  Admins sollen keine MasterEditor Berechtigungen haben, wenn sie nur Editor sind

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#309]
**Beschreibung**
Derzeit haben Administratoren auch dann MasterEditor Berechtigungen, wenn sie in einer Workgroup lediglich Editor sind.

Das macht sich folgend bemerkbar:
- in der Rolle "Editor" im Reiter "Nutzung" kann man die Externe Nutzung bearbeiten und speichern, nicht aber die Interne Nutzung (da wird eine Fehlermeldung ausgegeben). Eine Bearbeitung der Nutzung sollte in der Editor-Rolle nicht möglich sein.
- in der Rolle "Editor" im Reiter "Administration" kann man den Arbeitsstatus auf "Publiziert" stellen, was in der Rolle Editor ebenfalls nicht möglich sein sollte.

**Erwartetes Verhalten**
Ein Administrator ist für das Bearbeiten an die bestehenden Rollenkonzepte gebunden.

**Comment by mPfifi** [comment]
Test
