### ISSUE TITLE
Bug: Suchfilter Favoriten blockiert Flow der Applikation

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#346]
**Beschreibung**
Die Änderungen aus dem Hotfix und aus #19 kollidieren und erstellen einen ungewollten Extra-Schritt bei jeder Suche. Es gibt dadurch Probleme bei Navigation zwischen Asset Favoriten und Normaler Suche sowie bei der Anzeige der Heat Map.

Beschreibung Marcel:
Die App startet auch gleich mit einem Suchresultat (sowohl DEV wie auch INT), und die normale Suche lässt sich nicht zurücksetzten, sondern kommt immer wieder hervor. Dies auch beim Wechsel von den zuvor gewählten Favoriten zurück zur normalen Suche (statt wie erwartet wieder die Heat Map erscheinen würde). Ist das immer derselbe Fehler?

Bei Direktauswahl von Assets über blaue Punkte/Rauten werden gleich alle vorhandenen Assets ausgewählt.
Erwartet: nur das ausgewählte Asset erscheint (Detailansicht); die umliegenden blauen Icons werden gedimmt, lassen sich aber weiterhin direkt auswählen, wobei die Detailanzeige entsprechend ändert (aktuell auf PROD).

**Erwartetes Verhalten**
Wechsel zwischen Favoriten & Normal, Heatmap, Selektieren eines blauen Punktes funktioniert alles wie gewohnt.

**Comment by mPfifi** [comment]
Funktioniert auf INT und DEV wieder wie gewohnt. Problem behoben, Issue nach done verschoben.
