### ISSUE TITLE
Bug: Studies verschwinden, wenn man ein Detail anwählt

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#356]
**Beschreibung**
Wenn man in die Heatmap reinzoomt und auf einen blauen Punkt klickt, dann erscheint die Detailansicht.
Bisher sind die restlichen blauen Punkte durchsichtig geworden, aber weiterhin sichtbar und klickbar.
Jetzt verschwinden sie stattdessen.
Das ursprüngliche Verhalten soll wiederhergestellt werden.

**Comment by mPfifi** [comment]
Funktioniert wieder gut und wie gehabt auf PROD.
--> Issue nach done verschoben.
