### ISSUE TITLE
Deployment to DEV environment

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#66]
Deployment to DEV environment
- Run installation
- setaup Database (backup from Prod)
- Test DEV
- Adapt pipelines (Actions)

**Comment by ga-ebp** [comment]
Missing: Domain-Name
DB-Access from external (ebp)

**Comment by ga-ebp** [comment]
Dev-Assets (https://dev-assets.swissgeol.ch/) is running.
