### ISSUE TITLE
Load PROD data of the asset DB into INT DB

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#67]
The data from the PROD DB should be transferred so that the asset appl. can be better tested on INT.

- Get DB Backup from PROD (Nils? Or can we do it ourselves?)
- Import backup into INT DB
- Delete users manually from the INT DB -> do we need a script to create a few users (bulk)? Will this always have to be done via Cognito in future?
- Analyse for updating the Elasticsearch index after updating the DB (https://ebpgroup.atlassian.net/wiki/spaces/223443/pages/2044755971/Elastic-Search+Assets)

Documents on PROD S3 are **not** transferred
Elasticsearch index are **not** updated

**Comment by ga-ebp** [comment]
I just inserted the asset-values to the INT-DB with a part-backup. The existing user are still present in the INT-DB.

**Comment by ga-ebp** [comment]
The Elasticsearch index will be updated from Daniel.
