### ISSUE TITLE
Swissgeol Disclaimer (Assets)

### ISSUE THREAD

**Issue by traffic1000** [swisstopo/swissgeol-assets-suite#70]
**Beschreibung**
Es muss ein Disclaimer gezeigt werden, vor die Applikation genutzt werden kann. 
Der Disclaimer muss akzeptiert werden. Er tauch nach jedem Reload der Applikation erneut auf.

Das Design soll sich an Boreholes anlehnen
![Image](https://github.com/user-attachments/assets/39ef8982-5778-4591-895b-a4bb7243d8a5)

**EN: Terms of service**
Limitation of liability
Although every care has been taken by the Federal Office of Topography swisstopo to ensure the accuracy of the information published, no guarantee can be given with regard to the accurate, reliable, up-to-date or complete nature of this information.

swisstopo reserves the right to alter or remove the content, in full or in part, without prior notice.

Liability claims against swisstopo for material or immaterial damage resulting from access to or use or non-use of the published information, from misuse of the connection or from technical faults are excluded.

Further legal provisions can be found here: https://www.swissgeol.ch/datenschutz-en/

**DE: Nutzungsbedingungen**
Haftung
Obwohl das Bundesamt für Landestopografie swisstopo mit aller Sorgfalt auf die Richtigkeit der veröffentlichten Informationen achtet, kann hinsichtlich der inhaltlichen Richtigkeit, Genauigkeit, Aktualität, Zuverlässigkeit und Vollständigkeit dieser Informationen keine Gewährleistung übernommen werden.

Swisstopo behält sich ausdrücklich vor, jederzeit Inhalte ohne Ankündigung ganz oder teilweise zu ändern, zu löschen oder zeitweise nicht zu veröffentlichen.

Haftungsansprüche gegen swisstopo wegen Schäden materieller oder immaterieller Art, welche aus dem Zugriff oder der Nutzung bzw. Nichtnutzung der veröffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische Störungen entstanden sind, werden ausgeschlossen.

Weitere rechtliche Bestimmungen finden sie hier: https://www.swissgeol.ch/datenschutz/

**FR: Conditions d'utilisation**
Responsabilité
Malgré la grande attention qu’il porte à la justesse des informations diffusées sur ce site, l’Office fédéral de topographie swisstopo ne peut endosser aucune responsabilité quant à la fidélité, à l’exactitude, à l’actualité, à la fiabilité et à l’intégralité de ces informations.

swisstopo se réserve expressément le droit de modifier en partie ou en totalité le contenu de ce site, de le supprimer ou d’en suspendre temporairement la diffusion, et ce à tout moment et sans avertissement préalable.

swisstopo ne saurait être tenu pour responsable des dommages matériels ou immatériels qui pourraient être causés par l’accès aux informations diffusées ou par leur utilisation ou non-utilisation, par le mauvais usage de la connexion ou par des problèmes techniques.

Pour plus d'informations légales, veuillez consulter le lien suivant: https://www.swissgeol.ch/datenschutz-fr/

**IT: Condizioni di utilizzo**
Responsabilità
Nonostante si presti grande attenzione all’esattezza delle informazioni pubblicate su questo sito, l’Ufficio federale di topografia swisstopo declina ogni responsabilità per la fedeltà, l’esattezza, l’attualità, l’affidabilità e la completezza di tali informazioni.

swisstopo si riserva esplicitamente il diritto in qualsiasi momento di modificare parzialmente o completamente il contenuto del sito, di cancellarlo o di sospenderne temporaneamente la pubblicazione, senza alcun preavviso.

swisstopo declina ogni responsabilità per danni materiali o immateriali derivanti dall’accesso alle informazioni diffuse, dall’uso o dal mancato uso del sito, oppure che sono riconducibili a un malfunzionamento del collegamento o a disturbi tecnici del sito.

Per ulteriori informazioni legali, consultare il seguente link: https://www.swissgeol.ch/datenschutz-it/

**Comment by mPfifi** [comment]
Ist korrekt, inkl. aktivem Link
