### ISSUE TITLE
#29 Multi-Language | Elasticsearch

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#80]
Subtask of #29 

**Acceptance criteria**

- Adjust search interface
- Include language array in elasticsearch index
- Ensure backend to handle the multi-language case
- Recreate index

**Comment by mPfifi** [comment]
Auf DEV getestet: mehrere Sprachen lassen sich auswählen und speichern. Suchfilter nach Sprachen funktionieren.
Sieht soweit gut aus, Ticket nach done verschoben.
