### ISSUE TITLE
Authentication: Login Flow when cancelling

### ISSUE THREAD

**Issue by vej-ananas** [swisstopo/swissgeol-assets-suite#83]
What should a User see when the login flow using eIAM is cancelled?

Currently, the emtpy Asset application with an infinite loading bar is shown.

Options:
- Automatic redirect to login screen
- Login button
- Access denied screen

**Comment by daniel-va** [comment]
@mPfifi Für nicht-angemeldete Benutzer wird jetzt neu ein Splash Screen angezeigt, ähnlich wie dies schon bei Boreholes der fall ist. Dieser wird auch für fehlgeschlagene und abgebrochene Anmeldeversuche verwendet, und wird auch nach dem Abmelden angezeigt.

Bitte prüfen, ob dieser wie erwartet funktioniert.

**Comment by mPfifi** [comment]
@daniel-va Ich habe es gerade auf DEV getestet, es wird nach dem Abmelden der folgende Screen angezeigt:

![Image](https://github.com/swisstopo/swissgeol-assets-suite/assets/160217184/6f61ebe5-ad24-4eb0-8733-18b2f84cc24b)

Ist das korrekt so? - Oder wie kann ich es anderswo testen?

**Comment by daniel-va** [comment]
Das ist korrekt so - nach dem Abmelden wird der Splash Screen angezeigt, dieser leitet aber direkt wieder auf die Anmeldemaske weiter. Wenn du in der eIAM-Anmeldung "Cancel" auswählst, solltest du auf den Screen zurückgeleitet werden.

**Comment by mPfifi** [comment]
Das scheint zu funktionieren. Ich komme jedenfalls auf den Login-Screen zurück. Ticket somit abgeschlossen.
